#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    #language
    # options for layers checkers
    enable_neomake = true
    enable_ale = false
    lint_on_the_fly = false

# color support
[[layers]]
name = 'colorscheme'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# c/c++
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'
show_cursor_error = true
# enable = false

[[layers]]
name = "lang#c"
clang_executable = "clang"
[layer.clang_std]
c = "c11"
cpp = "c++1z"
objc = "c11"
objcpp = "c++1z"

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
]
[layers.override_cmd]
c = ["clangd"]
cpp = ["clangd"]

# java support
[[layers]]
name = "lang#java"

[[layers]]
name = "format"

# git support
[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

# tags
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"
  default_position = 'left'
  default_width = 30

[[custom_plugins]]
   repo = 'altercation/vim-colors-solarized'
   # note: you need to disable merged feature
   merged = false

[[custom_plugins]]
   repo = 'rootkiter/vim-hexedit'
   # note: you need to disable merged feature
   merged = false

# change cursor
[[custom_plugins]]
   repo = 'wincent/terminus'
   merged = false

# markdown support
[[custom_plugins]]
   repo = 'iamcco/markdown-preview.nvim'
   merged = false
