#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = " Yahei_Consolas_Hybrid:h11"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    #language
    # options for layers checkers
    enable_neomake =  true
    enable_ale =  false
    lint_on_the_fly = false

    default_indent = 4
    #custom setting
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"

    autocomplete_method = "coc"

# color support
[[layers]]
name = 'colorscheme'

[[layers]]
    name = 'ui'

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# c/c++
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "complete"

[[layers]]
name = 'checkers'
show_cursor_error = true

[[layers]]
name = "lang#c"
clang_executable = "clang"
[layer.clang_std]
c = "c11"
cpp = "c++1z"

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
]
enabled_clients = ['pylsp','clangd']
[layers.override_cmd]
c = ["clangd"]
cpp = ["clangd"]

# java support
[[layers]]
name = "lang#java"

# git support
[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

# tags
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"
  default_position = 'left'
  default_width = 30

[[custom_plugins]]
   repo = 'altercation/vim-colors-solarized'
   # note: you need to disable merged feature
   merged = false

[[custom_plugins]]
   repo = 'rootkiter/vim-hexedit'
   # note: you need to disable merged feature
   merged = false

# change cursor
[[custom_plugins]]
   repo = 'wincent/terminus'
   merged = false

# markdown support
[[layers]]
  name = "lang#markdown"
   
[[custom_plugins]]
   repo = 'iamcco/markdown-preview.nvim'
   merged = false

# cmake support
[[layers]]
  name = "lang#cmake"

# python support
[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

# shell-language support
[[layers]]
  name = "lang#sh"
# debug support
[[layers]]
  name = "debug"
	debugger_plugin = "vimspector"
